SYSTEM date
Use wikipedia

-- **********
DROP TABLE IF EXISTS pt320K;
CREATE TABLE pt320K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '',
 INDEX (title))
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/pt320K.csv'
INTO TABLE pt320K;

DROP TABLE IF EXISTS lpt1K;
CREATE TABLE lpt1K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt1K.csv'
INTO TABLE lpt1K;

UPDATE lpt1K, pt320K
SET lpt1K.id = pt320K.id
WHERE lpt1K.title = pt320K.title;

DROP TABLE lpt1K;

-- **********
DROP TABLE IF EXISTS lpt5K;
CREATE TABLE lpt5K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt5K.csv'
INTO TABLE lpt5K;

UPDATE lpt5K, pt320K
SET lpt5K.id = pt320K.id
WHERE lpt5K.title = pt320K.title;

DROP TABLE lpt5K;

DROP TABLE IF EXISTS lpt10K;
CREATE TABLE lpt10K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt10K.csv'
INTO TABLE lpt10K;

UPDATE lpt10K, pt320K
SET lpt10K.id = pt320K.id
WHERE lpt10K.title = pt320K.title;

DROP TABLE lpt10K;

-- **********
DROP TABLE IF EXISTS lpt20K;
CREATE TABLE lpt20K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt20K.csv'
INTO TABLE lpt20K;

UPDATE lpt20K, pt320K
SET lpt20K.id = pt320K.id
WHERE lpt20K.title = pt320K.title;

DROP TABLE lpt20K;

-- **********
DROP TABLE IF EXISTS lpt40K;
CREATE TABLE lpt40K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt40K.csv'
INTO TABLE lpt40K;

UPDATE lpt40K, pt320K
SET lpt40K.id = pt320K.id
WHERE lpt40K.title = pt320K.title;

DROP TABLE lpt40K;

-- **********
DROP TABLE IF EXISTS lpt80K;
CREATE TABLE lpt80K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt80K.csv'
INTO TABLE lpt80K;

UPDATE lpt80K, pt320K
SET lpt80K.id = pt320K.id
WHERE lpt80K.title = pt320K.title;

DROP TABLE lpt80K;

-- **********
DROP TABLE IF EXISTS lpt160K;
CREATE TABLE lpt160K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt160K.csv'
INTO TABLE lpt160K;

UPDATE lpt160K, pt320K
SET lpt160K.id = pt320K.id
WHERE lpt160K.title = pt320K.title;

DROP TABLE lpt160K;

-- **********
DROP TABLE IF EXISTS lpt320K;
CREATE TABLE lpt320K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt320K.csv'
INTO TABLE lpt320K;

UPDATE lpt320K, pt320K
SET lpt320K.id = pt320K.id
WHERE lpt320K.title = pt320K.title;

DROP TABLE lpt320K;
DROP TABLE pt320K;

-- **********
DROP TABLE IF EXISTS pt1280K;
CREATE TABLE pt1280K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '',
 INDEX (title))
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/pt1280K.csv'
INTO TABLE pt1280K;

DROP TABLE IF EXISTS lpt640K;
CREATE TABLE lpt640K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt640K.csv'
INTO TABLE lpt640K;

UPDATE lpt640K, pt1280K
SET lpt640K.id = pt1280K.id
WHERE lpt640K.title = pt1280K.title;

DROP TABLE lpt640K;

-- **********
DROP TABLE IF EXISTS lpt1280K;
CREATE TABLE lpt1280K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt1280K.csv'
INTO TABLE lpt1280K;

UPDATE lpt1280K, pt1280K
SET lpt1280K.id = pt1280K.id
WHERE lpt1280K.title = pt1280K.title;

DROP TABLE lpt1280K;
DROP TABLE pt1280K;

-- **********
DROP TABLE IF EXISTS pt2560K;
CREATE TABLE pt2560K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '',
 INDEX (title))
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/pt2560K.csv'
INTO TABLE pt2560K;

DROP TABLE IF EXISTS lpt2560K;
CREATE TABLE lpt2560K (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt2560K.csv'
INTO TABLE lpt2560K;

UPDATE lpt2560K, pt2560K
SET lpt2560K.id = pt2560K.id
WHERE lpt2560K.title = pt2560K.title;

DROP TABLE lpt2560K;
DROP TABLE pt2560K;

-- **********
DROP TABLE IF EXISTS pt5M;
CREATE TABLE pt5M (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '',
 INDEX (title))
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/pt5M.csv'
INTO TABLE pt5M;

DROP TABLE IF EXISTS lpt5M;
CREATE TABLE lpt5M (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt5M.csv'
INTO TABLE lpt5M;

UPDATE lpt5M, pt5M
SET lpt5M.id = pt5M.id
WHERE lpt5M.title = pt5M.title;

DROP TABLE lpt5M;
DROP TABLE pt5M;

-- **********
DROP TABLE IF EXISTS pt10M;
CREATE TABLE pt10M (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '',
 INDEX (title))
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/pt10M.csv'
INTO TABLE pt10M;

DROP TABLE IF EXISTS lpt10M;
CREATE TABLE lpt10M (
 id INT(8) UNSIGNED NOT NULL DEFAULT 0,
 title VARBINARY(60) NOT NULL DEFAULT '')
ENGINE = MyISAM DEFAULT CHARSET = BINARY;

LOAD DATA INFILE '/home/rasbar/coursework/e6893/project/tables/lpt10M.csv'
INTO TABLE lpt10M;

UPDATE lpt10M, pt10M
SET lpt10M.id = pt10M.id
WHERE lpt10M.title = pt10M.title;

DROP TABLE lpt10M;
DROP TABLE pt10M;

